addCollaborators:
  newCollaboratorMessage: "hi"
  existingCollaboratorMessage: "hi"
remindMerge:
  unmerged: "hi"
  merged: "hi"
checkPath:
  name: "File path"
  path: "_pins"
  detailsURL: "https://vimeo.com/201011288"
  success: "Your file is in the proper path."
  failure: "Your file is not in the _pins directory. Click details for instructions on how to fix."
checkExtension:
  name: "File extension"
  extension: "txt"
  detailsURL: "https://vimeo.com/201011288"
  success: "Your file has the proper extension."
  failure: "Your file extension is not .txt. Click details for instructions on how to fix."
